language: csharp
solution: SilverTongue.sln
mono: none
dotnet: 2.1.401
os:
  - linux
  - osx
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ProjectCeilidh.SilverTongue.Tests/ProjectCeilidh.SilverTongue.Tests.csproj